### ISSUE TITLE
Add "account locked" exception to known errors

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/ruby-bgs#84]
Today, we saw a Sentry alert with the following expection:
```
Savon::SOAPFault: (S:Client) ID: E51D976F-D132-422E-BC14-FD4070004401: Your account is locked.  Please contact your Security Officer
```
I think this should be included in the list of known errors that we can ignore in Sentry since it is not actionable. In this case, this came from a request to the IDT API endpoint, so the user received the error body.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5867/

**Comment by pkarman** [comment]
I disagree. This kind of authentication error is definitely actionable and we would want to know about it.

**Comment by monfresh** [comment]
I was wrong in making that assumption. Do you know what this means and how it's actionable? Should we create a custom error for this scenario?

**Comment by pkarman** [comment]
Yes, a custom error class makes sense.

This error is due to a CSEM account check. Apps that use this library would want to catch that error and probably return a 403 response to the original request, that includes the upstream error message. Since this library is used by other apps than just Caseflow, I think we should strive to only ignore transient HTTP (transport) related errors and create custom error classes for everything else.

**Comment by alisan16** [comment]
This error was last seen 8 months ago on Aug 13, 2019 12:19:21 PM EDT. Closing out. Can be reopened if it returns at a high enough frequency
